- hosts: all

  tasks:
# Basic deploy of a service
    - terraform:
        project_path: '.'
        state: present

    # init
    - terraform:
        project_path: '.'
        state: "{{ state }}"
        force_init: true